name: Prod Deployment

on:
  push: 
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: "12"

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: yarn deploy
      run:  yarn deploy
      env:
        CDK_STAGE: "prod"
